/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        
        import React, { useRef } from 'react'
        import { useGLTF, 
        
         } from '@react-three/drei'
        
        
        export default function Ruins(props) {
          const group = useRef()
          const { nodes, materials } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/ruins/model.gltf')
          return (
            <group ref={group} {...props} dispose={null}>
        <group position={[207.75, 1.48, -4.36,]} scale={[0.31, 0.27, 0.31,]} >
<mesh geometry={nodes.Cube049.geometry} material={materials.lightGrey} />
<mesh geometry={nodes.Cube049_1.geometry} material={materials.Grey} />
</group>

            </group>
          )
        }

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/ruins/model.gltf')
